APPL_DATA_PATH = "res/aapl-min-data.txt"
MSFT_DATA_PATH = "res/msft-min-data.txt"

DATE_FORMAT = "%m/%d/%Y"
TIME_FORMAT = "%H:%M"
DATETIME_FORMAT = DATE_FORMAT + " " + TIME_FORMAT

TIME_COLUMN = "Time"
DATE_COLUMN = "Date"
DATETIME_COLUMN = "DateTime"
HIGH_COLUMN = "High"
LOW_COLUMN = "Low"
CLOSE_COLUMN = "Close"
UP_COLUMN = "Up"
DOWN_COLUMN = "Down"

CHAIKIN_PERIOD = 10
VOL_PERIOD = 14
BOLLINGER_PERIOD = 20

CHAIKIN_ALPHA = 2 / (CHAIKIN_PERIOD + 1)
BOLLINGER_MULTIPLIER = 2
